import * as fs from 'fs';
import * as path from 'path';
import { addressToBytes32 } from './helpers';
import { FlowLog } from './types';

/**
 * Appends a detailed markdown section to output.md documenting
 * a full bridge execution (all 5 steps with tx hashes and parameters).
 */
export function appendToOutputMd(log: FlowLog): void {
  const outputPath = path.resolve(__dirname, '..', 'output.md');
  const isNew = !fs.existsSync(outputPath);

  let md = '';

  if (isNew) {
    md += '# PRUV Bridge — RWA Token Transfer Logs\n\n';
    md += 'Auto-generated by the RWA bridge script. Each section documents a full bridge execution.\n\n';
  }

  md += `---\n\n`;
  md += `## Bridge Transfer — ${log.timestamp}\n\n`;

  // ── Configuration ────────────────────────────────────────
  md += `### Configuration\n\n`;
  md += `| Parameter | Value |\n`;
  md += `|-----------|-------|\n`;
  md += `| Source Chain | ${log.sourceChain.name} (domain ${log.sourceChain.domainId}) |\n`;
  md += `| Destination Chain | ${log.destinationChain.name} (domain ${log.destinationChain.domainId}) |\n`;
  md += `| Sender | \`${log.sender}\` |\n`;
  md += `| Recipient | \`${log.recipient}\` |\n`;
  md += `| Token Address | \`${log.tokenAddress}\` |\n`;
  md += `| Token Amount | ${log.tokenAmount} |\n`;
  md += `| Token Amount (raw) | ${log.tokenAmountRaw} |\n\n`;

  // ── Quote Results ────────────────────────────────────────
  md += `### Step 1: quoteTransferRemote\n\n`;
  md += `| Quote | Token | Amount (raw) | Amount (formatted) |\n`;
  md += `|-------|-------|-------------|--------------------|\n`;
  md += `| Gas Payment | native | ${log.gasQuote.raw} | ${log.gasQuote.formatted} |\n`;
  md += `| Transfer Token | \`${log.transferToken.address}\` (${log.transferToken.symbol}) | ${log.transferToken.amount} | ${log.transferToken.formatted} ${log.transferToken.symbol} |\n`;
  if (log.feeToken) {
    md += `| Fee Token | \`${log.feeToken.address}\` (${log.feeToken.symbol}) | ${log.feeToken.amount} | ${log.feeToken.formatted} ${log.feeToken.symbol} |\n`;
  } else {
    md += `| Fee Token | — | 0 | No fee |\n`;
  }
  md += `\n`;

  // ── Approvals ────────────────────────────────────────────
  md += `### Step 2: Transfer Token Approval\n\n`;
  if (log.approvalTxHash) {
    md += `- **Tx Hash**: \`${log.approvalTxHash}\`\n`;
    md += `- **Explorer**: ${log.sourceChain.explorerTxUrl}${log.approvalTxHash}\n`;
  } else {
    md += `- Already approved (no tx needed)\n`;
  }
  md += `\n`;

  md += `### Step 3: Fee Token Approval\n\n`;
  if (log.feeApprovalTxHash) {
    md += `- **Tx Hash**: \`${log.feeApprovalTxHash}\`\n`;
    md += `- **Explorer**: ${log.sourceChain.explorerTxUrl}${log.feeApprovalTxHash}\n`;
  } else if (log.feeToken) {
    md += `- Already approved (no tx needed)\n`;
  } else {
    md += `- No fee token — skipped\n`;
  }
  md += `\n`;

  // ── Transfer ─────────────────────────────────────────────
  md += `### Step 4: transferRemote\n\n`;
  md += `| Parameter | Value |\n`;
  md += `|-----------|-------|\n`;
  md += `| Tx Hash | \`${log.transferTxHash || 'N/A'}\` |\n`;
  md += `| Explorer | ${log.transferTxHash ? `${log.sourceChain.explorerTxUrl}${log.transferTxHash}` : 'N/A'} |\n`;
  md += `| Block | ${log.transferBlock ?? 'N/A'} |\n`;
  md += `| Gas Used | ${log.transferGasUsed ?? 'N/A'} |\n`;
  md += `| Status | ${log.transferStatus ?? 'N/A'} |\n`;
  md += `| destination (domain) | ${log.destinationChain.domainId} |\n`;
  md += `| recipient (bytes32) | \`${addressToBytes32(log.recipient)}\` |\n`;
  md += `| amountOrId | ${log.tokenAmountRaw} |\n`;
  md += `| msg.value | ${log.gasQuote.raw} |\n\n`;

  // ── Relay / Delivery ─────────────────────────────────────
  md += `### Step 5: Destination Delivery (ReceivedTransferRemote)\n\n`;
  if (log.relayStatus === 'Delivered') {
    md += `| Parameter | Value |\n`;
    md += `|-----------|-------|\n`;
    md += `| Tx Hash | \`${log.relayTxHash}\` |\n`;
    md += `| Explorer | ${log.destinationChain.explorerTxUrl}${log.relayTxHash} |\n`;
    md += `| Block | ${log.relayBlock} |\n`;
    md += `| Amount Received | ${log.relayAmount} |\n`;
    md += `| Status | ✅ Delivered |\n`;
  } else if (log.relayStatus === 'Timeout') {
    md += `- ⚠ Timed out waiting for delivery. The relayer may still deliver later.\n`;
  } else {
    md += `- Skipped\n`;
  }
  md += `\n`;

  fs.appendFileSync(outputPath, md);
  console.log(`\n📄 Flow details appended to output.md`);
}
