import * as fs from 'fs';
import * as path from 'path';
import { FlowLog } from './types';

/**
 * Appends a detailed markdown section to output.md documenting
 * a full redeem flow execution (3 phases).
 */
export function appendToOutputMd(log: FlowLog): void {
  const outputPath = path.resolve(__dirname, '..', 'output.md');
  const isNew = !fs.existsSync(outputPath);

  let md = '';

  if (isNew) {
    md += '# PRUV Bridge — Redeem Flow Logs\n\n';
    md += 'Auto-generated by the redeem flow script. Each section documents a full redeem flow execution.\n\n';
    md += 'Flow: Bridge RWA (Kaia → Pruv) → Redeem RWA → USDT (Pruv vault) → Bridge USDT (Pruv → Kaia)\n\n';
  }

  md += `---\n\n`;
  md += `## Redeem Flow — ${log.timestamp}\n\n`;

  // ── Overview ──
  md += `### Overview\n\n`;
  md += `| Parameter | Value |\n`;
  md += `|-----------|-------|\n`;
  md += `| Sender | \`${log.sender}\` |\n`;
  md += `| Recipient | \`${log.recipient}\` |\n`;
  md += `| RWA Amount | ${log.rwaAmount} |\n`;
  md += `\n`;

  // ── Phase 1: Bridge RWA Kaia → Pruv ──
  md += `### Phase 1: Bridge RWA (${log.phase1.sourceChain} → ${log.phase1.destinationChain})\n\n`;
  md += `| Step | Value |\n`;
  md += `|------|-------|\n`;
  md += `| Token | \`${log.phase1.tokenAddress}\` (${log.phase1.tokenSymbol}) |\n`;
  md += `| Gas Quote | ${log.phase1.gasQuote.formatted} |\n`;
  if (log.phase1.approvalTxHash) {
    md += `| Approval Tx | \`${log.phase1.approvalTxHash}\` |\n`;
  }
  if (log.phase1.transferTxHash) {
    md += `| Transfer Tx | \`${log.phase1.transferTxHash}\` |\n`;
  }
  md += `| Transfer Status | ${log.phase1.transferStatus ?? 'N/A'} |\n`;
  md += `| Relay Status | ${log.phase1.relayStatus ?? 'N/A'} |\n`;
  if (log.phase1.relayTxHash) {
    md += `| Relay Tx | \`${log.phase1.relayTxHash}\` |\n`;
  }
  md += `\n`;

  // ── Phase 2: Redeem RWA → USDT ──
  md += `### Phase 2: Redeem RWA → USDT (Pruv Vault Redeem)\n\n`;
  md += `| Step | Value |\n`;
  md += `|------|-------|\n`;
  md += `| Vault | \`${log.phase2.vaultAddress}\` |\n`;
  md += `| RWA Token | \`${log.phase2.rwaTokenAddress}\` (${log.phase2.rwaTokenSymbol}) |\n`;
  md += `| Shares Redeemed | ${log.phase2.sharesRedeemed} |\n`;
  if (log.phase2.redeemTxHash) {
    md += `| Redeem Tx | \`${log.phase2.redeemTxHash}\` |\n`;
  }
  md += `| Redeem Status | ${log.phase2.redeemStatus ?? 'N/A'} |\n`;
  if (log.phase2.assetsReceived) {
    md += `| Assets Received | ${log.phase2.assetsReceived} ${log.phase2.assetSymbol ?? 'USDT'} |\n`;
  }
  md += `\n`;

  // ── Phase 3: Bridge USDT Pruv → Kaia ──
  md += `### Phase 3: Bridge USDT (${log.phase3.sourceChain} → ${log.phase3.destinationChain})\n\n`;
  md += `| Step | Value |\n`;
  md += `|------|-------|\n`;
  md += `| Token | \`${log.phase3.tokenAddress}\` (${log.phase3.tokenSymbol}) |\n`;
  md += `| USDT Amount | ${log.phase3.usdtAmount} |\n`;
  md += `| Gas Quote | ${log.phase3.gasQuote.formatted} |\n`;
  if (log.phase3.approvalTxHash) {
    md += `| Approval Tx | \`${log.phase3.approvalTxHash}\` |\n`;
  }
  if (log.phase3.transferTxHash) {
    md += `| Transfer Tx | \`${log.phase3.transferTxHash}\` |\n`;
  }
  md += `| Transfer Status | ${log.phase3.transferStatus ?? 'N/A'} |\n`;
  md += `| Relay Status | ${log.phase3.relayStatus ?? 'N/A'} |\n`;
  if (log.phase3.relayTxHash) {
    md += `| Relay Tx | \`${log.phase3.relayTxHash}\` |\n`;
  }
  md += `\n`;

  fs.appendFileSync(outputPath, md, 'utf-8');
  console.log(`\n📝 Flow log appended to ${outputPath}`);
}
