import * as fs from 'fs';
import * as path from 'path';
import { FlowLog } from './types';

/**
 * Appends a detailed markdown section to output.md documenting
 * a full mint flow execution (3 phases).
 */
export function appendToOutputMd(log: FlowLog): void {
  const outputPath = path.resolve(__dirname, '..', 'output.md');
  const isNew = !fs.existsSync(outputPath);

  let md = '';

  if (isNew) {
    md += '# PRUV Bridge — Mint Flow Logs\n\n';
    md += 'Auto-generated by the mint flow script. Each section documents a full mint flow execution.\n\n';
    md += 'Flow: Bridge USDT (Kaia → Pruv) → Mint RWA (Pruv vault) → Bridge RWA (Pruv → Kaia)\n\n';
  }

  md += `---\n\n`;
  md += `## Mint Flow — ${log.timestamp}\n\n`;

  // ── Overview ──
  md += `### Overview\n\n`;
  md += `| Parameter | Value |\n`;
  md += `|-----------|-------|\n`;
  md += `| Sender | \`${log.sender}\` |\n`;
  md += `| Recipient | \`${log.recipient}\` |\n`;
  md += `| USDT Amount | ${log.usdtAmount} |\n`;
  md += `\n`;

  // ── Phase 1: Bridge USDT Kaia → Pruv ──
  md += `### Phase 1: Bridge USDT (${log.phase1.sourceChain} → ${log.phase1.destinationChain})\n\n`;
  md += `| Step | Value |\n`;
  md += `|------|-------|\n`;
  md += `| Token | \`${log.phase1.tokenAddress}\` (${log.phase1.tokenSymbol}) |\n`;
  md += `| Gas Quote | ${log.phase1.gasQuote.formatted} |\n`;
  if (log.phase1.approvalTxHash) {
    md += `| Approval Tx | \`${log.phase1.approvalTxHash}\` |\n`;
  }
  if (log.phase1.transferTxHash) {
    md += `| Transfer Tx | \`${log.phase1.transferTxHash}\` |\n`;
  }
  md += `| Transfer Status | ${log.phase1.transferStatus ?? 'N/A'} |\n`;
  md += `| Relay Status | ${log.phase1.relayStatus ?? 'N/A'} |\n`;
  if (log.phase1.relayTxHash) {
    md += `| Relay Tx | \`${log.phase1.relayTxHash}\` |\n`;
  }
  md += `\n`;

  // ── Phase 2: Mint RWA on Pruv ──
  md += `### Phase 2: Mint RWA (Pruv Vault Deposit)\n\n`;
  md += `| Step | Value |\n`;
  md += `|------|-------|\n`;
  md += `| Vault | \`${log.phase2.vaultAddress}\` |\n`;
  md += `| Deposit Asset | \`${log.phase2.depositAsset}\` (${log.phase2.depositAssetSymbol}) |\n`;
  md += `| Deposit Amount | ${log.phase2.depositAmount} |\n`;
  if (log.phase2.depositApprovalTxHash) {
    md += `| Deposit Approval Tx | \`${log.phase2.depositApprovalTxHash}\` |\n`;
  }
  if (log.phase2.depositTxHash) {
    md += `| Deposit Tx | \`${log.phase2.depositTxHash}\` |\n`;
  }
  md += `| Deposit Status | ${log.phase2.depositStatus ?? 'N/A'} |\n`;
  if (log.phase2.sharesReceived) {
    md += `| Shares Received | ${log.phase2.sharesReceived} (${log.phase2.rwaTokenSymbol ?? 'RWA'}) |\n`;
  }
  md += `\n`;

  // ── Phase 3: Bridge RWA Pruv → Kaia ──
  md += `### Phase 3: Bridge RWA (${log.phase3.sourceChain} → ${log.phase3.destinationChain})\n\n`;
  md += `| Step | Value |\n`;
  md += `|------|-------|\n`;
  md += `| Token | \`${log.phase3.tokenAddress}\` (${log.phase3.tokenSymbol}) |\n`;
  md += `| RWA Amount | ${log.phase3.rwaAmount} |\n`;
  md += `| Gas Quote | ${log.phase3.gasQuote.formatted} |\n`;
  if (log.phase3.feeToken) {
    md += `| Fee Token | \`${log.phase3.feeToken.address}\` (${log.phase3.feeToken.symbol}) |\n`;
    md += `| Fee Amount | ${log.phase3.feeToken.formatted} |\n`;
  }
  if (log.phase3.approvalTxHash) {
    md += `| Approval Tx | \`${log.phase3.approvalTxHash}\` |\n`;
  }
  if (log.phase3.feeApprovalTxHash) {
    md += `| Fee Approval Tx | \`${log.phase3.feeApprovalTxHash}\` |\n`;
  }
  if (log.phase3.transferTxHash) {
    md += `| Transfer Tx | \`${log.phase3.transferTxHash}\` |\n`;
  }
  md += `| Transfer Status | ${log.phase3.transferStatus ?? 'N/A'} |\n`;
  md += `| Relay Status | ${log.phase3.relayStatus ?? 'N/A'} |\n`;
  if (log.phase3.relayTxHash) {
    md += `| Relay Tx | \`${log.phase3.relayTxHash}\` |\n`;
  }
  md += `\n`;

  fs.appendFileSync(outputPath, md, 'utf-8');
  console.log(`\n📝 Flow log appended to ${outputPath}`);
}
